# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qorder', '0021_porcionessemana_semanasgu_semanasre_suministros_suministros_gu_suministros_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='semanasgu',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('NROEQUIP', models.FloatField(verbose_name='NROEQUIP', blank=True, null=True)),
                ('PORCION', models.CharField(verbose_name='PORCION', blank=True, max_length=100, null=True)),
                ('DIST', models.SmallIntegerField(verbose_name='DIST', blank=True, null=True)),
                ('UNIDAD', models.CharField(verbose_name='UNIDAD', blank=True, max_length=100, null=True)),
                ('NROPUERT', models.FloatField(verbose_name='NROPUERT', blank=True, null=True)),
                ('SEC', models.SmallIntegerField(verbose_name='SEC', blank=True, null=True)),
                ('INTERLOC', models.FloatField(verbose_name='INTERLOC', blank=True, null=True)),
                ('CLIENTE', models.CharField(verbose_name='CLIENTE', blank=True, max_length=100, null=True)),
                ('CALLE', models.CharField(verbose_name='CALLE', blank=True, max_length=100, null=True)),
                ('DIREXION', models.FloatField(verbose_name='DIREXION', blank=True, null=True)),
                ('CORTE', models.CharField(verbose_name='CORTE', blank=True, max_length=100, null=True)),
                ('NROSERIE', models.CharField(verbose_name='NROSERIE', blank=True, max_length=100, null=True)),
                ('CLASE_AP', models.CharField(verbose_name='CLASE_AP', blank=True, max_length=100, null=True)),
                ('MARCA', models.CharField(verbose_name='MARCA', blank=True, max_length=100, null=True)),
                ('TEX_DIV', models.CharField(verbose_name='TEX_DIV', blank=True, max_length=100, null=True)),
                ('DIAMED', models.CharField(verbose_name='DIAMED', blank=True, max_length=100, null=True)),
                ('CONS_EST', models.FloatField(verbose_name='CONS_EST', blank=True, null=True)),
                ('CONS_MIN', models.FloatField(verbose_name='CONS_MIN', blank=True, null=True)),
                ('CONS_MAX', models.FloatField(verbose_name='CONS_MAX', blank=True, null=True)),
                ('INC_1', models.SmallIntegerField(verbose_name='INC_1', blank=True, null=True)),
                ('LECT_1', models.FloatField(verbose_name='LECT_1', blank=True, null=True)),
                ('CONS_1', models.FloatField(verbose_name='CONS_1', blank=True, null=True)),
                ('PLANIF_1', models.FloatField(verbose_name='PLANIF_1', blank=True, null=True)),
                ('INC_2', models.SmallIntegerField(verbose_name='INC_2', blank=True, null=True)),
                ('LECT_2', models.FloatField(verbose_name='LECT_2', blank=True, null=True)),
                ('CONS_2', models.FloatField(verbose_name='CONS_2', blank=True, null=True)),
                ('PLANIF_2', models.FloatField(verbose_name='PLANIF_2', blank=True, null=True)),
                ('INC_3', models.SmallIntegerField(verbose_name='INC_3', blank=True, null=True)),
                ('LECT_3', models.FloatField(verbose_name='LECT_3', blank=True, null=True)),
                ('CONS_3', models.FloatField(verbose_name='CONS_3', blank=True, null=True)),
                ('PLANIF_3', models.FloatField(verbose_name='PLANIF_3', blank=True, null=True)),
                ('INC_4', models.SmallIntegerField(verbose_name='INC_4', blank=True, null=True)),
                ('LECT_4', models.FloatField(verbose_name='LECT_4', blank=True, null=True)),
                ('CONS_4', models.FloatField(verbose_name='CONS_4', blank=True, null=True)),
                ('PLANIF_4', models.FloatField(verbose_name='PLANIF_4', blank=True, null=True)),
                ('INC_5', models.SmallIntegerField(verbose_name='INC_5', blank=True, null=True)),
                ('LECT_5', models.FloatField(verbose_name='LECT_5', blank=True, null=True)),
                ('CONS_5', models.FloatField(verbose_name='CONS_5', blank=True, null=True)),
                ('PLANIF_5', models.FloatField(verbose_name='PLANIF_5', blank=True, null=True)),
                ('INC_6', models.SmallIntegerField(verbose_name='INC_6', blank=True, null=True)),
                ('LECT_6', models.FloatField(verbose_name='LECT_6', blank=True, null=True)),
                ('CONS_6', models.FloatField(verbose_name='CONS_6', blank=True, null=True)),
                ('PLANIF_6', models.FloatField(verbose_name='PLANIF_6', blank=True, null=True)),
                ('INC_REC', models.SmallIntegerField(verbose_name='INC_REC', blank=True, null=True)),
                ('LEC_RET', models.FloatField(verbose_name='LEC_RET', blank=True, null=True)),
                ('CONS_RET', models.FloatField(verbose_name='CONS_RET', blank=True, null=True)),
                ('FEC_REC', models.FloatField(verbose_name='FEC_REC', blank=True, null=True)),
                ('CON_ACUM', models.FloatField(verbose_name='CON_ACUM', blank=True, null=True)),
                ('ULT_LECT', models.FloatField(verbose_name='ULT_LECT', blank=True, null=True)),
                ('ANIO_INS', models.CharField(verbose_name='ANIO_INS', blank=True, max_length=100, null=True)),
                ('TIPO_CON', models.CharField(verbose_name='TIPO_CON', blank=True, max_length=100, null=True)),
                ('DIGITOS', models.SmallIntegerField(verbose_name='DIGITOS', blank=True, null=True)),
                ('CODPOST', models.CharField(verbose_name='CODPOST', blank=True, max_length=100, null=True)),
                ('DCSM', models.CharField(verbose_name='DCSM', blank=True, max_length=100, null=True)),
                ('PORCION_ORIGINAL', models.CharField(verbose_name='PORCION_ORIGINAL', blank=True, max_length=100, null=True)),
                ('SEC_ORIGINAL', models.SmallIntegerField(verbose_name='SEC_ORIGINAL', blank=True, null=True)),
                ('DISTRITO', models.CharField(verbose_name='DISTRITO', blank=True, max_length=100, null=True)),
                ('CIRC', models.CharField(verbose_name='CIRC', blank=True, max_length=100, null=True)),
                ('SECCION', models.CharField(verbose_name='SECCION', blank=True, max_length=100, null=True)),
                ('MANZANA', models.CharField(verbose_name='MANZANA', blank=True, max_length=100, null=True)),
                ('UNIDAD_ORIGINAL', models.CharField(verbose_name='UNIDAD_ORIGINAL', blank=True, max_length=100, null=True)),
                ('ORDENADO_POR', models.CharField(verbose_name='ORDENADO_POR', blank=True, max_length=100, null=True)),
                ('SEC_RELACIONADA', models.IntegerField(verbose_name='SEC_RELACIONADA', blank=True, null=True)),
                ('LAT', models.FloatField(verbose_name='LAT', blank=True, null=True)),
                ('LON', models.FloatField(verbose_name='LON', blank=True, null=True)),
                ('SEMANA', models.SmallIntegerField(verbose_name='SEMANA', blank=True, null=True)),
                ('EXP', models.CharField(verbose_name='EXP', blank=True, max_length=100, null=True)),
                ('EXPSAP', models.CharField(verbose_name='EXPSAP', blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'semanasgu',
                'verbose_name_plural': 'semanasgu',
            },
        ),
        migrations.CreateModel(
            name='semanasre',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('NROEQUIP', models.FloatField(verbose_name='NROEQUIP', blank=True, null=True)),
                ('PORCION', models.CharField(verbose_name='PORCION', blank=True, max_length=100, null=True)),
                ('DIST', models.SmallIntegerField(verbose_name='DIST', blank=True, null=True)),
                ('UNIDAD', models.CharField(verbose_name='UNIDAD', blank=True, max_length=100, null=True)),
                ('NROPUERT', models.FloatField(verbose_name='NROPUERT', blank=True, null=True)),
                ('SEC', models.SmallIntegerField(verbose_name='SEC', blank=True, null=True)),
                ('INTERLOC', models.FloatField(verbose_name='INTERLOC', blank=True, null=True)),
                ('CLIENTE', models.CharField(verbose_name='CLIENTE', blank=True, max_length=100, null=True)),
                ('CALLE', models.CharField(verbose_name='CALLE', blank=True, max_length=100, null=True)),
                ('DIREXION', models.FloatField(verbose_name='DIREXION', blank=True, null=True)),
                ('CORTE', models.CharField(verbose_name='CORTE', blank=True, max_length=100, null=True)),
                ('NROSERIE', models.CharField(verbose_name='NROSERIE', blank=True, max_length=100, null=True)),
                ('CLASE_AP', models.CharField(verbose_name='CLASE_AP', blank=True, max_length=100, null=True)),
                ('MARCA', models.CharField(verbose_name='MARCA', blank=True, max_length=100, null=True)),
                ('TEX_DIV', models.CharField(verbose_name='TEX_DIV', blank=True, max_length=100, null=True)),
                ('DIAMED', models.CharField(verbose_name='DIAMED', blank=True, max_length=100, null=True)),
                ('CONS_EST', models.FloatField(verbose_name='CONS_EST', blank=True, null=True)),
                ('CONS_MIN', models.FloatField(verbose_name='CONS_MIN', blank=True, null=True)),
                ('CONS_MAX', models.FloatField(verbose_name='CONS_MAX', blank=True, null=True)),
                ('INC_1', models.SmallIntegerField(verbose_name='INC_1', blank=True, null=True)),
                ('LECT_1', models.FloatField(verbose_name='LECT_1', blank=True, null=True)),
                ('CONS_1', models.FloatField(verbose_name='CONS_1', blank=True, null=True)),
                ('PLANIF_1', models.FloatField(verbose_name='PLANIF_1', blank=True, null=True)),
                ('INC_2', models.SmallIntegerField(verbose_name='INC_2', blank=True, null=True)),
                ('LECT_2', models.FloatField(verbose_name='LECT_2', blank=True, null=True)),
                ('CONS_2', models.FloatField(verbose_name='CONS_2', blank=True, null=True)),
                ('PLANIF_2', models.FloatField(verbose_name='PLANIF_2', blank=True, null=True)),
                ('INC_3', models.SmallIntegerField(verbose_name='INC_3', blank=True, null=True)),
                ('LECT_3', models.FloatField(verbose_name='LECT_3', blank=True, null=True)),
                ('CONS_3', models.FloatField(verbose_name='CONS_3', blank=True, null=True)),
                ('PLANIF_3', models.FloatField(verbose_name='PLANIF_3', blank=True, null=True)),
                ('INC_4', models.SmallIntegerField(verbose_name='INC_4', blank=True, null=True)),
                ('LECT_4', models.FloatField(verbose_name='LECT_4', blank=True, null=True)),
                ('CONS_4', models.FloatField(verbose_name='CONS_4', blank=True, null=True)),
                ('PLANIF_4', models.FloatField(verbose_name='PLANIF_4', blank=True, null=True)),
                ('INC_5', models.SmallIntegerField(verbose_name='INC_5', blank=True, null=True)),
                ('LECT_5', models.FloatField(verbose_name='LECT_5', blank=True, null=True)),
                ('CONS_5', models.FloatField(verbose_name='CONS_5', blank=True, null=True)),
                ('PLANIF_5', models.FloatField(verbose_name='PLANIF_5', blank=True, null=True)),
                ('INC_6', models.SmallIntegerField(verbose_name='INC_6', blank=True, null=True)),
                ('LECT_6', models.FloatField(verbose_name='LECT_6', blank=True, null=True)),
                ('CONS_6', models.FloatField(verbose_name='CONS_6', blank=True, null=True)),
                ('PLANIF_6', models.FloatField(verbose_name='PLANIF_6', blank=True, null=True)),
                ('INC_REC', models.SmallIntegerField(verbose_name='INC_REC', blank=True, null=True)),
                ('LEC_RET', models.FloatField(verbose_name='LEC_RET', blank=True, null=True)),
                ('CONS_RET', models.FloatField(verbose_name='CONS_RET', blank=True, null=True)),
                ('FEC_REC', models.FloatField(verbose_name='FEC_REC', blank=True, null=True)),
                ('CON_ACUM', models.FloatField(verbose_name='CON_ACUM', blank=True, null=True)),
                ('ULT_LECT', models.FloatField(verbose_name='ULT_LECT', blank=True, null=True)),
                ('ANIO_INS', models.CharField(verbose_name='ANIO_INS', blank=True, max_length=100, null=True)),
                ('TIPO_CON', models.CharField(verbose_name='TIPO_CON', blank=True, max_length=100, null=True)),
                ('DIGITOS', models.SmallIntegerField(verbose_name='DIGITOS', blank=True, null=True)),
                ('CODPOST', models.CharField(verbose_name='CODPOST', blank=True, max_length=100, null=True)),
                ('DCSM', models.CharField(verbose_name='DCSM', blank=True, max_length=100, null=True)),
                ('PORCION_ORIGINAL', models.CharField(verbose_name='PORCION_ORIGINAL', blank=True, max_length=100, null=True)),
                ('SEC_ORIGINAL', models.SmallIntegerField(verbose_name='SEC_ORIGINAL', blank=True, null=True)),
                ('DISTRITO', models.CharField(verbose_name='DISTRITO', blank=True, max_length=100, null=True)),
                ('CIRC', models.CharField(verbose_name='CIRC', blank=True, max_length=100, null=True)),
                ('SECCION', models.CharField(verbose_name='SECCION', blank=True, max_length=100, null=True)),
                ('MANZANA', models.CharField(verbose_name='MANZANA', blank=True, max_length=100, null=True)),
                ('UNIDAD_ORIGINAL', models.CharField(verbose_name='UNIDAD_ORIGINAL', blank=True, max_length=100, null=True)),
                ('ORDENADO_POR', models.CharField(verbose_name='ORDENADO_POR', blank=True, max_length=100, null=True)),
                ('SEC_RELACIONADA', models.IntegerField(verbose_name='SEC_RELACIONADA', blank=True, null=True)),
                ('LAT', models.FloatField(verbose_name='LAT', blank=True, null=True)),
                ('LON', models.FloatField(verbose_name='LON', blank=True, null=True)),
                ('SEMANA', models.SmallIntegerField(verbose_name='SEMANA', blank=True, null=True)),
                ('EXP', models.CharField(verbose_name='EXP', blank=True, max_length=100, null=True)),
                ('EXPSAP', models.CharField(verbose_name='EXPSAP', blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'semanasre',
                'verbose_name_plural': 'semanasre',
            },
        ),
        migrations.CreateModel(
            name='suministros',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('COD_UNICOM', models.CharField(verbose_name='COD_UNICOM', blank=True, max_length=100, null=True)),
                ('RUTA', models.CharField(verbose_name='RUTA', blank=True, max_length=100, null=True)),
                ('ITINERARIO', models.CharField(verbose_name='ITINERARIO', blank=True, max_length=100, null=True)),
                ('CICLO', models.CharField(verbose_name='CICLO', blank=True, max_length=100, null=True)),
                ('ANIO', models.CharField(verbose_name='ANIO', blank=True, max_length=100, null=True)),
                ('SEG_REG', models.CharField(verbose_name='SEG_REG', blank=True, max_length=100, null=True)),
                ('DIVISION', models.CharField(verbose_name='DIVISION', blank=True, max_length=100, null=True)),
                ('SECUENCIA', models.IntegerField(verbose_name='SECUENCIA', blank=True, null=True)),
                ('LOCALIDAD', models.CharField(verbose_name='LOCALIDAD', blank=True, max_length=100, null=True)),
                ('NOMBRE_CLIENTE', models.CharField(verbose_name='NOMBRE_CLIENTE', blank=True, max_length=100, null=True)),
                ('DIRECCION', models.CharField(verbose_name='DIRECCION', blank=True, max_length=100, null=True)),
                ('NRO_PUERTA', models.DecimalField(decimal_places=7, max_digits=10)),
                ('PISO', models.CharField(verbose_name='PISO', blank=True, max_length=100, null=True)),
                ('DUPLICADOR', models.CharField(verbose_name='DUPLICADOR', blank=True, max_length=100, null=True)),
                ('NRO_APARTO', models.CharField(verbose_name='NRO_APARTO', blank=True, max_length=100, null=True)),
                ('COD_MARCA', models.CharField(verbose_name='COD_MARCA', blank=True, max_length=100, null=True)),
                ('RUEDAS', models.SmallIntegerField(verbose_name='RUEDAS', blank=True, null=True)),
                ('MULTIPLICADOR', models.SmallIntegerField(verbose_name='MULTIPLICADOR', blank=True, null=True)),
                ('LECTURA_ANTERIOR', models.DecimalField(decimal_places=7, max_digits=10)),
                ('LECTURA_MINIMA', models.DecimalField(decimal_places=7, max_digits=10)),
                ('LECTURA_MAXIMA', models.DecimalField(decimal_places=7, max_digits=10)),
                ('DESC_CONSUMO', models.CharField(verbose_name='DESC_CONSUMO', blank=True, max_length=100, null=True)),
                ('ACCESO_FINCA', models.CharField(verbose_name='ACCESO_FINCA', blank=True, max_length=100, null=True)),
                ('ACCESO_PM', models.CharField(verbose_name='ACCESO_PM', blank=True, max_length=100, null=True)),
                ('ESTADO_LECT', models.CharField(verbose_name='ESTADO_LECT', blank=True, max_length=100, null=True)),
                ('ESTADO_SUM', models.CharField(verbose_name='ESTADO_SUM', blank=True, max_length=100, null=True)),
                ('ESTADO_ACT', models.CharField(verbose_name='ESTADO_ACT', blank=True, max_length=100, null=True)),
                ('COD_TARIFA', models.CharField(verbose_name='COD_TARIFA', blank=True, max_length=100, null=True)),
                ('LECTURA_ACTUAL', models.DecimalField(decimal_places=7, max_digits=10)),
                ('TIP_CONSUMO', models.CharField(verbose_name='TIP_CONSUMO', blank=True, max_length=100, null=True)),
                ('FH_LECTURA', models.CharField(verbose_name='FH_LECTURA', blank=True, max_length=100, null=True)),
                ('CONSUMO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CANT_LECT_FORZADA', models.IntegerField(verbose_name='CANT_LECT_FORZADA', blank=True, null=True)),
                ('NRO_LECTURISTA', models.IntegerField(verbose_name='NRO_LECTURISTA', blank=True, null=True)),
                ('COD_COLECTOR', models.CharField(verbose_name='COD_COLECTOR', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA_HH_1', models.CharField(verbose_name='COD_ANOMALIA_HH_1', blank=True, max_length=100, null=True)),
                ('NOTAS1', models.CharField(verbose_name='NOTAS1', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA_HH_2', models.CharField(verbose_name='COD_ANOMALIA_HH_2', blank=True, max_length=100, null=True)),
                ('NOTAS2', models.CharField(verbose_name='NOTAS2', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA_HH_3', models.CharField(verbose_name='COD_ANOMALIA_HH_3', blank=True, max_length=100, null=True)),
                ('NOTAS3', models.CharField(verbose_name='NOTAS3', blank=True, max_length=100, null=True)),
                ('SECUENCIA_REAL', models.IntegerField(verbose_name='SECUENCIA_REAL', blank=True, null=True)),
                ('NRO_CLIENTE', models.CharField(verbose_name='NRO_CLIENTE', blank=True, max_length=100, null=True)),
                ('COMPLEMENTO', models.CharField(verbose_name='COMPLEMENTO', blank=True, max_length=100, null=True)),
                ('CONSUMO_ESTIMADO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('COD_ANOMALIA1', models.CharField(verbose_name='COD_ANOMALIA1', blank=True, max_length=100, null=True)),
                ('LECTURA1', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO1', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA1', models.CharField(verbose_name='FECHA_LECTURA1', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA2', models.CharField(verbose_name='COD_ANOMALIA2', blank=True, max_length=100, null=True)),
                ('LECTURA2', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO2', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA2', models.CharField(verbose_name='FECHA_LECTURA2', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA3', models.CharField(verbose_name='COD_ANOMALIA3', blank=True, max_length=100, null=True)),
                ('LECTURA3', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO3', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA3', models.CharField(verbose_name='FECHA_LECTURA3', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA4', models.CharField(verbose_name='COD_ANOMALIA4', blank=True, max_length=100, null=True)),
                ('LECTURA4', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO4', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA4', models.CharField(verbose_name='FECHA_LECTURA4', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA5', models.CharField(verbose_name='COD_ANOMALIA5', blank=True, max_length=100, null=True)),
                ('LECTURA5', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO5', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA5', models.CharField(verbose_name='FECHA_LECTURA5', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA6', models.CharField(verbose_name='COD_ANOMALIA6', blank=True, max_length=100, null=True)),
                ('LECTURA6', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO6', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA6', models.CharField(verbose_name='FECHA_LECTURA6', blank=True, max_length=100, null=True)),
                ('COD_RECAMBIO', models.CharField(verbose_name='COD_RECAMBIO', blank=True, max_length=100, null=True)),
                ('LEC_MEDIDOR_RETIRADO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO_ULTIMO_RECAMBIO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_RECAMBIO', models.CharField(verbose_name='FECHA_RECAMBIO', blank=True, max_length=100, null=True)),
                ('ACUM_CONS_VARIOS_RECAMBIOS', models.DecimalField(decimal_places=7, max_digits=10)),
                ('ANIO_INSTALACION', models.DecimalField(decimal_places=7, max_digits=10)),
                ('COD_TIPO_CONEXION', models.CharField(verbose_name='COD_TIPO_CONEXION', blank=True, max_length=100, null=True)),
                ('TIPO_MEDIDOR', models.CharField(verbose_name='TIPO_MEDIDOR', blank=True, max_length=100, null=True)),
                ('COD_DIAMETRO', models.CharField(verbose_name='COD_DIAMETRO', blank=True, max_length=100, null=True)),
                ('CONSULTO_HISTORICOS', models.CharField(verbose_name='CONSULTO_HISTORICOS', blank=True, max_length=100, null=True)),
                ('COD_ESTADO_CONEXION', models.CharField(verbose_name='COD_ESTADO_CONEXION', blank=True, max_length=100, null=True)),
                ('NRO_LECTURISTA_AUDITORIA', models.IntegerField(verbose_name='NRO_LECTURISTA_AUDITORIA', blank=True, null=True)),
                ('COD_UNICOM_LECT_AUDIT', models.CharField(verbose_name='COD_UNICOM_LECT_AUDIT', blank=True, max_length=100, null=True)),
                ('COD_COLECTOR_AUDITORIA', models.IntegerField(verbose_name='COD_COLECTOR_AUDITORIA', blank=True, null=True)),
                ('COD_UNICOM_COLEC_AUDIT', models.CharField(verbose_name='COD_UNICOM_COLEC_AUDIT', blank=True, max_length=100, null=True)),
                ('FH_LECTURA_AUDIT', models.CharField(verbose_name='FH_LECTURA_AUDIT', blank=True, max_length=100, null=True)),
                ('LECTURA_ACTUAL_AUDIT', models.DecimalField(decimal_places=7, max_digits=10)),
                ('COD_ANOMALIA_HH_1_AUDIT', models.CharField(verbose_name='COD_ANOMALIA_HH_1_AUDIT', blank=True, max_length=100, null=True)),
                ('NOTAS1_AUDIT', models.CharField(verbose_name='NOTAS1_AUDIT', blank=True, max_length=100, null=True)),
                ('GPS_LATITUD', models.CharField(verbose_name='GPS_LATITUD', blank=True, max_length=100, null=True)),
                ('GPS_LONGITUD', models.CharField(verbose_name='GPS_LONGITUD', blank=True, max_length=100, null=True)),
                ('PORCION_ORIGINAL', models.CharField(verbose_name='PORCION_ORIGINAL', blank=True, max_length=100, null=True)),
                ('SEC_ORIGINAL', models.IntegerField(verbose_name='SEC_ORIGINAL', blank=True, null=True)),
                ('UNIDAD_ORIGINAL', models.CharField(verbose_name='UNIDAD_ORIGINAL', blank=True, max_length=100, null=True)),
                ('CODPOST', models.CharField(verbose_name='CODPOST', blank=True, max_length=100, null=True)),
                ('DCSM', models.CharField(verbose_name='DCSM', blank=True, max_length=100, null=True)),
                ('DISTRITO', models.CharField(verbose_name='DISTRITO', blank=True, max_length=100, null=True)),
                ('CIRC', models.CharField(verbose_name='CIRC', blank=True, max_length=100, null=True)),
                ('SECCION', models.CharField(verbose_name='SECCION', blank=True, max_length=100, null=True)),
                ('MANZANA', models.CharField(verbose_name='MANZANA', blank=True, max_length=100, null=True)),
                ('ORDENADO_POR', models.CharField(verbose_name='ORDENADO_POR', blank=True, max_length=100, null=True)),
                ('SEC_RELACIONADA', models.IntegerField(verbose_name='SEC_RELACIONADA', blank=True, null=True)),
                ('LAT', models.FloatField(verbose_name='LAT', blank=True, null=True)),
                ('LON', models.FloatField(verbose_name='LON', blank=True, null=True)),
            ],
            options={
                'verbose_name': 'suministros',
                'verbose_name_plural': 'suministros',
            },
        ),
        migrations.CreateModel(
            name='suministros_gu',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('COD_UNICOM', models.CharField(verbose_name='COD_UNICOM', blank=True, max_length=100, null=True)),
                ('RUTA', models.CharField(verbose_name='RUTA', blank=True, max_length=100, null=True)),
                ('ITINERARIO', models.CharField(verbose_name='ITINERARIO', blank=True, max_length=100, null=True)),
                ('CICLO', models.CharField(verbose_name='CICLO', blank=True, max_length=100, null=True)),
                ('ANIO', models.CharField(verbose_name='ANIO', blank=True, max_length=100, null=True)),
                ('SEG_REG', models.CharField(verbose_name='SEG_REG', blank=True, max_length=100, null=True)),
                ('DIVISION', models.CharField(verbose_name='DIVISION', blank=True, max_length=100, null=True)),
                ('SECUENCIA', models.IntegerField(verbose_name='SECUENCIA', blank=True, null=True)),
                ('LOCALIDAD', models.CharField(verbose_name='LOCALIDAD', blank=True, max_length=100, null=True)),
                ('NOMBRE_CLIENTE', models.CharField(verbose_name='NOMBRE_CLIENTE', blank=True, max_length=100, null=True)),
                ('DIRECCION', models.CharField(verbose_name='DIRECCION', blank=True, max_length=100, null=True)),
                ('NRO_PUERTA', models.DecimalField(decimal_places=7, max_digits=10)),
                ('PISO', models.CharField(verbose_name='PISO', blank=True, max_length=100, null=True)),
                ('DUPLICADOR', models.CharField(verbose_name='DUPLICADOR', blank=True, max_length=100, null=True)),
                ('NRO_APARTO', models.CharField(verbose_name='NRO_APARTO', blank=True, max_length=100, null=True)),
                ('COD_MARCA', models.CharField(verbose_name='COD_MARCA', blank=True, max_length=100, null=True)),
                ('RUEDAS', models.SmallIntegerField(verbose_name='RUEDAS')),
                ('MULTIPLICADOR', models.SmallIntegerField(verbose_name='MULTIPLICADOR')),
                ('LECTURA_ANTERIOR', models.DecimalField(decimal_places=7, max_digits=10)),
                ('LECTURA_MINIMA', models.DecimalField(decimal_places=7, max_digits=10)),
                ('LECTURA_MAXIMA', models.DecimalField(decimal_places=7, max_digits=10)),
                ('DESC_CONSUMO', models.CharField(verbose_name='DESC_CONSUMO', blank=True, max_length=100, null=True)),
                ('ACCESO_FINCA', models.CharField(verbose_name='ACCESO_FINCA', blank=True, max_length=100, null=True)),
                ('ACCESO_PM', models.CharField(verbose_name='ACCESO_PM', blank=True, max_length=100, null=True)),
                ('ESTADO_LECT', models.CharField(verbose_name='ESTADO_LECT', blank=True, max_length=100, null=True)),
                ('ESTADO_SUM', models.CharField(verbose_name='ESTADO_SUM', blank=True, max_length=100, null=True)),
                ('ESTADO_ACT', models.CharField(verbose_name='ESTADO_ACT', blank=True, max_length=100, null=True)),
                ('COD_TARIFA', models.CharField(verbose_name='COD_TARIFA', blank=True, max_length=100, null=True)),
                ('LECTURA_ACTUAL', models.DecimalField(decimal_places=7, max_digits=10)),
                ('TIP_CONSUMO', models.CharField(verbose_name='TIP_CONSUMO', blank=True, max_length=100, null=True)),
                ('FH_LECTURA', models.CharField(verbose_name='FH_LECTURA', blank=True, max_length=100, null=True)),
                ('CONSUMO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CANT_LECT_FORZADA', models.IntegerField(verbose_name='CANT_LECT_FORZADA', blank=True, null=True)),
                ('NRO_LECTURISTA', models.IntegerField(verbose_name='NRO_LECTURISTA', blank=True, null=True)),
                ('COD_COLECTOR', models.CharField(verbose_name='COD_COLECTOR', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA_HH_1', models.CharField(verbose_name='COD_ANOMALIA_HH_1', blank=True, max_length=100, null=True)),
                ('NOTAS1', models.CharField(verbose_name='NOTAS1', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA_HH_2', models.CharField(verbose_name='COD_ANOMALIA_HH_2', blank=True, max_length=100, null=True)),
                ('NOTAS2', models.CharField(verbose_name='NOTAS2', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA_HH_3', models.CharField(verbose_name='COD_ANOMALIA_HH_3', blank=True, max_length=100, null=True)),
                ('NOTAS3', models.CharField(verbose_name='NOTAS3', blank=True, max_length=100, null=True)),
                ('SECUENCIA_REAL', models.IntegerField(verbose_name='SECUENCIA_REAL', blank=True, null=True)),
                ('NRO_CLIENTE', models.CharField(verbose_name='NRO_CLIENTE', blank=True, max_length=100, null=True)),
                ('COMPLEMENTO', models.CharField(verbose_name='COMPLEMENTO', blank=True, max_length=100, null=True)),
                ('CONSUMO_ESTIMADO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('COD_ANOMALIA1', models.CharField(verbose_name='COD_ANOMALIA1', blank=True, max_length=100, null=True)),
                ('LECTURA1', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO1', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA1', models.CharField(verbose_name='FECHA_LECTURA1', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA2', models.CharField(verbose_name='COD_ANOMALIA2', blank=True, max_length=100, null=True)),
                ('LECTURA2', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO2', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA2', models.CharField(verbose_name='FECHA_LECTURA2', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA3', models.CharField(verbose_name='COD_ANOMALIA3', blank=True, max_length=100, null=True)),
                ('LECTURA3', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO3', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA3', models.CharField(verbose_name='FECHA_LECTURA3', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA4', models.CharField(verbose_name='COD_ANOMALIA4', blank=True, max_length=100, null=True)),
                ('LECTURA4', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO4', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA4', models.CharField(verbose_name='FECHA_LECTURA4', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA5', models.CharField(verbose_name='COD_ANOMALIA5', blank=True, max_length=100, null=True)),
                ('LECTURA5', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO5', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA5', models.CharField(verbose_name='FECHA_LECTURA5', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA6', models.CharField(verbose_name='COD_ANOMALIA6', blank=True, max_length=100, null=True)),
                ('LECTURA6', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO6', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA6', models.CharField(verbose_name='FECHA_LECTURA6', blank=True, max_length=100, null=True)),
                ('COD_RECAMBIO', models.CharField(verbose_name='COD_RECAMBIO', blank=True, max_length=100, null=True)),
                ('LEC_MEDIDOR_RETIRADO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO_ULTIMO_RECAMBIO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_RECAMBIO', models.CharField(verbose_name='FECHA_RECAMBIO', blank=True, max_length=100, null=True)),
                ('ACUM_CONS_VARIOS_RECAMBIOS', models.DecimalField(decimal_places=7, max_digits=10)),
                ('ANIO_INSTALACION', models.DecimalField(decimal_places=7, max_digits=10)),
                ('COD_TIPO_CONEXION', models.CharField(verbose_name='COD_TIPO_CONEXION', blank=True, max_length=100, null=True)),
                ('TIPO_MEDIDOR', models.CharField(verbose_name='TIPO_MEDIDOR', blank=True, max_length=100, null=True)),
                ('COD_DIAMETRO', models.CharField(verbose_name='COD_DIAMETRO', blank=True, max_length=100, null=True)),
                ('CONSULTO_HISTORICOS', models.CharField(verbose_name='CONSULTO_HISTORICOS', blank=True, max_length=100, null=True)),
                ('COD_ESTADO_CONEXION', models.CharField(verbose_name='COD_ESTADO_CONEXION', blank=True, max_length=100, null=True)),
                ('NRO_LECTURISTA_AUDITORIA', models.IntegerField(verbose_name='NRO_LECTURISTA_AUDITORIA', blank=True, null=True)),
                ('COD_UNICOM_LECT_AUDIT', models.CharField(verbose_name='COD_UNICOM_LECT_AUDIT', blank=True, max_length=100, null=True)),
                ('COD_COLECTOR_AUDITORIA', models.IntegerField(verbose_name='COD_COLECTOR_AUDITORIA', blank=True, null=True)),
                ('COD_UNICOM_COLEC_AUDIT', models.CharField(verbose_name='COD_UNICOM_COLEC_AUDIT', blank=True, max_length=100, null=True)),
                ('FH_LECTURA_AUDIT', models.CharField(verbose_name='FH_LECTURA_AUDIT', blank=True, max_length=100, null=True)),
                ('LECTURA_ACTUAL_AUDIT', models.DecimalField(decimal_places=7, max_digits=10)),
                ('COD_ANOMALIA_HH_1_AUDIT', models.CharField(verbose_name='COD_ANOMALIA_HH_1_AUDIT', blank=True, max_length=100, null=True)),
                ('NOTAS1_AUDIT', models.CharField(verbose_name='NOTAS1_AUDIT', blank=True, max_length=100, null=True)),
                ('GPS_LATITUD', models.CharField(verbose_name='GPS_LATITUD', blank=True, max_length=100, null=True)),
                ('GPS_LONGITUD', models.CharField(verbose_name='GPS_LONGITUD', blank=True, max_length=100, null=True)),
                ('PORCION_ORIGINAL', models.CharField(verbose_name='PORCION_ORIGINAL', blank=True, max_length=100, null=True)),
                ('SEC_ORIGINAL', models.IntegerField(verbose_name='SEC_ORIGINAL', blank=True, null=True)),
                ('UNIDAD_ORIGINAL', models.CharField(verbose_name='UNIDAD_ORIGINAL', blank=True, max_length=100, null=True)),
                ('CODPOST', models.CharField(verbose_name='CODPOST', blank=True, max_length=100, null=True)),
                ('DCSM', models.CharField(verbose_name='DCSM', blank=True, max_length=100, null=True)),
                ('DISTRITO', models.CharField(verbose_name='DISTRITO', blank=True, max_length=100, null=True)),
                ('CIRC', models.CharField(verbose_name='CIRC', blank=True, max_length=100, null=True)),
                ('SECCION', models.CharField(verbose_name='SECCION', blank=True, max_length=100, null=True)),
                ('MANZANA', models.CharField(verbose_name='MANZANA', blank=True, max_length=100, null=True)),
                ('ORDENADO_POR', models.CharField(verbose_name='ORDENADO_POR', blank=True, max_length=100, null=True)),
                ('SEC_RELACIONADA', models.IntegerField(verbose_name='SEC_RELACIONADA', blank=True, null=True)),
                ('LAT', models.FloatField(verbose_name='LAT')),
                ('LON', models.FloatField(verbose_name='LON')),
            ],
            options={
                'verbose_name': 'suministros_gu',
                'verbose_name_plural': 'suministros_gu',
            },
        ),
        migrations.CreateModel(
            name='suministros_res',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('COD_UNICOM', models.CharField(verbose_name='COD_UNICOM', blank=True, max_length=100, null=True)),
                ('RUTA', models.CharField(verbose_name='RUTA', blank=True, max_length=100, null=True)),
                ('ITINERARIO', models.CharField(verbose_name='ITINERARIO', blank=True, max_length=100, null=True)),
                ('CICLO', models.CharField(verbose_name='CICLO', blank=True, max_length=100, null=True)),
                ('ANIO', models.CharField(verbose_name='ANIO', blank=True, max_length=100, null=True)),
                ('SEG_REG', models.CharField(verbose_name='SEG_REG', blank=True, max_length=100, null=True)),
                ('DIVISION', models.CharField(verbose_name='DIVISION', blank=True, max_length=100, null=True)),
                ('SECUENCIA', models.IntegerField(verbose_name='SECUENCIA', blank=True, null=True)),
                ('LOCALIDAD', models.CharField(verbose_name='LOCALIDAD', blank=True, max_length=100, null=True)),
                ('NOMBRE_CLIENTE', models.CharField(verbose_name='NOMBRE_CLIENTE', blank=True, max_length=100, null=True)),
                ('DIRECCION', models.CharField(verbose_name='DIRECCION', blank=True, max_length=100, null=True)),
                ('NRO_PUERTA', models.DecimalField(decimal_places=7, max_digits=10)),
                ('PISO', models.CharField(verbose_name='PISO', blank=True, max_length=100, null=True)),
                ('DUPLICADOR', models.CharField(verbose_name='DUPLICADOR', blank=True, max_length=100, null=True)),
                ('NRO_APARTO', models.CharField(verbose_name='NRO_APARTO', blank=True, max_length=100, null=True)),
                ('COD_MARCA', models.CharField(verbose_name='COD_MARCA', blank=True, max_length=100, null=True)),
                ('RUEDAS', models.SmallIntegerField(verbose_name='RUEDAS')),
                ('MULTIPLICADOR', models.SmallIntegerField(verbose_name='MULTIPLICADOR')),
                ('LECTURA_ANTERIOR', models.DecimalField(decimal_places=7, max_digits=10)),
                ('LECTURA_MINIMA', models.DecimalField(decimal_places=7, max_digits=10)),
                ('LECTURA_MAXIMA', models.DecimalField(decimal_places=7, max_digits=10)),
                ('DESC_CONSUMO', models.CharField(verbose_name='DESC_CONSUMO', blank=True, max_length=100, null=True)),
                ('ACCESO_FINCA', models.CharField(verbose_name='ACCESO_FINCA', blank=True, max_length=100, null=True)),
                ('ACCESO_PM', models.CharField(verbose_name='ACCESO_PM', blank=True, max_length=100, null=True)),
                ('ESTADO_LECT', models.CharField(verbose_name='ESTADO_LECT', blank=True, max_length=100, null=True)),
                ('ESTADO_SUM', models.CharField(verbose_name='ESTADO_SUM', blank=True, max_length=100, null=True)),
                ('ESTADO_ACT', models.CharField(verbose_name='ESTADO_ACT', blank=True, max_length=100, null=True)),
                ('COD_TARIFA', models.CharField(verbose_name='COD_TARIFA', blank=True, max_length=100, null=True)),
                ('LECTURA_ACTUAL', models.DecimalField(decimal_places=7, max_digits=10)),
                ('TIP_CONSUMO', models.CharField(verbose_name='TIP_CONSUMO', blank=True, max_length=100, null=True)),
                ('FH_LECTURA', models.CharField(verbose_name='FH_LECTURA', blank=True, max_length=100, null=True)),
                ('CONSUMO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CANT_LECT_FORZADA', models.IntegerField(verbose_name='CANT_LECT_FORZADA', blank=True, null=True)),
                ('NRO_LECTURISTA', models.IntegerField(verbose_name='NRO_LECTURISTA', blank=True, null=True)),
                ('COD_COLECTOR', models.CharField(verbose_name='COD_COLECTOR', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA_HH_1', models.CharField(verbose_name='COD_ANOMALIA_HH_1', blank=True, max_length=100, null=True)),
                ('NOTAS1', models.CharField(verbose_name='NOTAS1', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA_HH_2', models.CharField(verbose_name='COD_ANOMALIA_HH_2', blank=True, max_length=100, null=True)),
                ('NOTAS2', models.CharField(verbose_name='NOTAS2', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA_HH_3', models.CharField(verbose_name='COD_ANOMALIA_HH_3', blank=True, max_length=100, null=True)),
                ('NOTAS3', models.CharField(verbose_name='NOTAS3', blank=True, max_length=100, null=True)),
                ('SECUENCIA_REAL', models.IntegerField(verbose_name='SECUENCIA_REAL', blank=True, null=True)),
                ('NRO_CLIENTE', models.CharField(verbose_name='NRO_CLIENTE', blank=True, max_length=100, null=True)),
                ('COMPLEMENTO', models.CharField(verbose_name='COMPLEMENTO', blank=True, max_length=100, null=True)),
                ('CONSUMO_ESTIMADO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('COD_ANOMALIA1', models.CharField(verbose_name='COD_ANOMALIA1', blank=True, max_length=100, null=True)),
                ('LECTURA1', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO1', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA1', models.CharField(verbose_name='FECHA_LECTURA1', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA2', models.CharField(verbose_name='COD_ANOMALIA2', blank=True, max_length=100, null=True)),
                ('LECTURA2', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO2', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA2', models.CharField(verbose_name='FECHA_LECTURA2', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA3', models.CharField(verbose_name='COD_ANOMALIA3', blank=True, max_length=100, null=True)),
                ('LECTURA3', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO3', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA3', models.CharField(verbose_name='FECHA_LECTURA3', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA4', models.CharField(verbose_name='COD_ANOMALIA4', blank=True, max_length=100, null=True)),
                ('LECTURA4', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO4', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA4', models.CharField(verbose_name='FECHA_LECTURA4', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA5', models.CharField(verbose_name='COD_ANOMALIA5', blank=True, max_length=100, null=True)),
                ('LECTURA5', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO5', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA5', models.CharField(verbose_name='FECHA_LECTURA5', blank=True, max_length=100, null=True)),
                ('COD_ANOMALIA6', models.CharField(verbose_name='COD_ANOMALIA6', blank=True, max_length=100, null=True)),
                ('LECTURA6', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO6', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_LECTURA6', models.CharField(verbose_name='FECHA_LECTURA6', blank=True, max_length=100, null=True)),
                ('COD_RECAMBIO', models.CharField(verbose_name='COD_RECAMBIO', blank=True, max_length=100, null=True)),
                ('LEC_MEDIDOR_RETIRADO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('CONSUMO_ULTIMO_RECAMBIO', models.DecimalField(decimal_places=7, max_digits=10)),
                ('FECHA_RECAMBIO', models.CharField(verbose_name='FECHA_RECAMBIO', blank=True, max_length=100, null=True)),
                ('ACUM_CONS_VARIOS_RECAMBIOS', models.DecimalField(decimal_places=7, max_digits=10)),
                ('ANIO_INSTALACION', models.DecimalField(decimal_places=7, max_digits=10)),
                ('COD_TIPO_CONEXION', models.CharField(verbose_name='COD_TIPO_CONEXION', blank=True, max_length=100, null=True)),
                ('TIPO_MEDIDOR', models.CharField(verbose_name='TIPO_MEDIDOR', blank=True, max_length=100, null=True)),
                ('COD_DIAMETRO', models.CharField(verbose_name='COD_DIAMETRO', blank=True, max_length=100, null=True)),
                ('CONSULTO_HISTORICOS', models.CharField(verbose_name='CONSULTO_HISTORICOS', blank=True, max_length=100, null=True)),
                ('COD_ESTADO_CONEXION', models.CharField(verbose_name='COD_ESTADO_CONEXION', blank=True, max_length=100, null=True)),
                ('NRO_LECTURISTA_AUDITORIA', models.IntegerField(verbose_name='NRO_LECTURISTA_AUDITORIA', blank=True, null=True)),
                ('COD_UNICOM_LECT_AUDIT', models.CharField(verbose_name='COD_UNICOM_LECT_AUDIT', blank=True, max_length=100, null=True)),
                ('COD_COLECTOR_AUDITORIA', models.IntegerField(verbose_name='COD_COLECTOR_AUDITORIA', blank=True, null=True)),
                ('COD_UNICOM_COLEC_AUDIT', models.CharField(verbose_name='COD_UNICOM_COLEC_AUDIT', blank=True, max_length=100, null=True)),
                ('FH_LECTURA_AUDIT', models.CharField(verbose_name='FH_LECTURA_AUDIT', blank=True, max_length=100, null=True)),
                ('LECTURA_ACTUAL_AUDIT', models.DecimalField(decimal_places=7, max_digits=10)),
                ('COD_ANOMALIA_HH_1_AUDIT', models.CharField(verbose_name='COD_ANOMALIA_HH_1_AUDIT', blank=True, max_length=100, null=True)),
                ('NOTAS1_AUDIT', models.CharField(verbose_name='NOTAS1_AUDIT', blank=True, max_length=100, null=True)),
                ('GPS_LATITUD', models.CharField(verbose_name='GPS_LATITUD', blank=True, max_length=100, null=True)),
                ('GPS_LONGITUD', models.CharField(verbose_name='GPS_LONGITUD', blank=True, max_length=100, null=True)),
                ('PORCION_ORIGINAL', models.CharField(verbose_name='PORCION_ORIGINAL', blank=True, max_length=100, null=True)),
                ('SEC_ORIGINAL', models.IntegerField(verbose_name='SEC_ORIGINAL', blank=True, null=True)),
                ('UNIDAD_ORIGINAL', models.CharField(verbose_name='UNIDAD_ORIGINAL', blank=True, max_length=100, null=True)),
                ('CODPOST', models.CharField(verbose_name='CODPOST', blank=True, max_length=100, null=True)),
                ('DCSM', models.CharField(verbose_name='DCSM', blank=True, max_length=100, null=True)),
                ('DISTRITO', models.CharField(verbose_name='DISTRITO', blank=True, max_length=100, null=True)),
                ('CIRC', models.CharField(verbose_name='CIRC', blank=True, max_length=100, null=True)),
                ('SECCION', models.CharField(verbose_name='SECCION', blank=True, max_length=100, null=True)),
                ('MANZANA', models.CharField(verbose_name='MANZANA', blank=True, max_length=100, null=True)),
                ('ORDENADO_POR', models.CharField(verbose_name='ORDENADO_POR', blank=True, max_length=100, null=True)),
                ('SEC_RELACIONADA', models.IntegerField(verbose_name='SEC_RELACIONADA', blank=True, null=True)),
                ('LAT', models.FloatField(verbose_name='LAT')),
                ('LON', models.FloatField(verbose_name='LON')),
            ],
            options={
                'verbose_name': 'suministros_res',
                'verbose_name_plural': 'suministros_res',
            },
        ),
    ]
