# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qorder', '0028_auto_20170727_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministros',
            name='CONSUMO1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='CONSUMO2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='CONSUMO3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='CONSUMO4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='CONSUMO5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='CONSUMO6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='LECTURA1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='LECTURA2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='LECTURA3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='LECTURA4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='LECTURA5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='LECTURA6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='CONSUMO1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='CONSUMO2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='CONSUMO3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='CONSUMO4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='CONSUMO5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='CONSUMO6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='LAT',
            field=models.FloatField(blank=True, verbose_name='LAT', null=True),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='LECTURA1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='LECTURA2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='LECTURA3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='LECTURA4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='LECTURA5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='LECTURA6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='LON',
            field=models.FloatField(blank=True, verbose_name='LON', null=True),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='MULTIPLICADOR',
            field=models.SmallIntegerField(blank=True, verbose_name='MULTIPLICADOR', null=True),
        ),
        migrations.AlterField(
            model_name='suministros_gu',
            name='RUEDAS',
            field=models.SmallIntegerField(blank=True, verbose_name='RUEDAS', null=True),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='CONSUMO1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='CONSUMO2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='CONSUMO3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='CONSUMO4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='CONSUMO5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='CONSUMO6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='LAT',
            field=models.FloatField(blank=True, verbose_name='LAT', null=True),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='LECTURA1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='LECTURA2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='LECTURA3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='LECTURA4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='LECTURA5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='LECTURA6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='LON',
            field=models.FloatField(blank=True, verbose_name='LON', null=True),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='MULTIPLICADOR',
            field=models.SmallIntegerField(blank=True, verbose_name='MULTIPLICADOR', null=True),
        ),
        migrations.AlterField(
            model_name='suministros_res',
            name='RUEDAS',
            field=models.SmallIntegerField(blank=True, verbose_name='RUEDAS', null=True),
        ),
    ]
