"""
Django settings for qorderweb project.

Generated by 'django-admin startproject' using Django 1.9.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from django.contrib import messages
import djcelery
djcelery.setup_loader()
from celery.schedules import crontab

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
print('BaseDir {}'.format(BASE_DIR))
APP_VERSION='1.0.19'

LOGIN_PAGE = '/qorderweb/login'
LOGIN_OK = '/qorderweb/'

LOGO_PATH = 'images/logo_aysa.png' 
LOGO_SIZE = '200px'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ofgqm)dla3$kcc%+$a8kwg^ntbwa#q(!%r($tv=&&zput^$rq)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

SECURE_HSTS_SECONDS = 10  # Unit is seconds; *USE A SMALL VALUE FOR TESTING!* for prd 2592000
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


# Application definition
CRISPY_TEMPLATE_PACK = 'bootstrap3'
CRISPY_FAIL_SILENTLY = DEBUG
DEFAULT_APPS = (
    'django_admin_bootstrapped',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'crispy_forms',
    'djcelery',
    'kombu.transport.django',
    
)

EMSER_APPS = (
    'core',
    'qorder',
    'rest_framework',
    'api',

)


FILE_UPLOAD_HANDLERS = (
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
)


INSTALLED_APPS = DEFAULT_APPS + EMSER_APPS 

BROKER_URL = 'amqp://guest:guest@localhost//'
CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'qorder.middleware.LogUserDetails',

    #'qorder.middleware.SqlPrintMiddleware',

]

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    )
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
AUTH_USER_MODEL = 'core.EmserUser'

#SEGURIDAD
SECURE_BROWSER_XSS_FILTER = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True


DATABASES = {
    'default': {
       'ENGINE': 'django.db.backends.mysql',
       'NAME': 'aysaqorder',
        'USER': 'aysaqorder',
        'PASSWORD': 'Sarmiento1150!',
#        'HOST':'aysaqorder-db-v2.cfg6ocmyps16.us-west-2.rds.amazonaws.com',   # Or an IP Address that your DB is hosted on
	'HOST':'aysaqorder-db-v3-cluster.cluster-ro-cfg6ocmyps16.us-west-2.rds.amazonaws.com',
       'PORT': '3306',}
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Cordoba'

USE_I18N = True

USE_L10N = False

USE_TZ = False #SE COLOCA FALSE PARA QUE LA HORA SEA LA CORRECTA


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

DAB_FIELD_RENDERER = 'django_admin_bootstrapped.renderers.BootstrapFieldRenderer'

MESSAGE_TAGS = {
            messages.SUCCESS: 'success',
            messages.WARNING: 'warning',
            messages.ERROR: 'error',
            messages.INFO: 'info'
}
from django.utils.translation import ugettext_lazy as _
LANGUAGES = (
    ('en', _('English')),
    ('pt-br', _('Portuguese')),
    ('es', _('Spanish')),
)


LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'conf/locale'),
)


VALIDAR_CON_E_SECURITY = 0
URL_WS_SCP = 'http://192.168.1.231/EPSAWS/service1.asmx?wsdl'
#URL_WS_SCP = 'http://leda:85/Authentication.svc'
APP_WS_SCP = 'ab7f439e-1198-49b2-9318-a2912eb54c69'


MINUTOS_INACTIVIDAD = 40
    

MAX_POINTS_IN_MAP = 10000


#EMSER CONFIGURATION
TITLE_SITE = 'Administración QOrder Web'

####
PROJECT_ROOT = os.path.dirname(os.path.abspath(__name__))
print(PROJECT_ROOT)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'static'),
)

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': True,
#     'filters': {
#         # Add an unbound RequestFilter.
#         'request': {
#             '()': 'django_requestlogging.logging_filters.RequestFilter',
#         },
#     },
#     'formatters': {
#         'request_format': {
#             'format': '%(remote_addr)s %(username)s "%(request_method)s '
#             '%(path_info)s %(server_protocol)s" %(http_user_agent)s '
#             '%(message)s %(asctime)s',
#         },
#         'standard': {

#             'format' : "%(asctime)-15s %(name)-5s %(levelname)-8s %(message)s",
#             'datefmt' : "%d/%b/%Y %H:%M:%S"
#         },
#     },

#     'handlers': {
#         'null': {
#             'level':'DEBUG',
#             'class':'django.utils.log.NullHandler',
#         },
#         'logfile': {
#             'level':'INFO',
#             'class':'logging.handlers.RotatingFileHandler',
#             # 'filename': BASE_DIR + "/QOrderLog",
#             'filename': "/var/log/django/QOrderLog_aysa.txt",
#             'maxBytes': 50000,
#             'backupCount': 2,

#             'formatter': 'standard',
#         },
#         'console':{
#             'level':'INFO',
#             'class':'logging.StreamHandler',
#             'formatter': 'standard'
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers':['console'],
#             'propagate': True,
#             'level':'WARN',
#         },
#         'django.db.backends': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#         'qorderweb': {
#             'handlers': ['console', 'logfile'],
#             'level': 'INFO',
#         },
#     }
# }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'filters': {
        # Add an unbound RequestFilter.
        'request': {
            '()': 'django_requestlogging.logging_filters.RequestFilter',
        },
    },
    'formatters': {
        'request_format': {
            'format': '%(remote_addr)s %(username)s "%(request_method)s '
                      '%(path_info)s %(server_protocol)s" %(http_user_agent)s '
                      '%(message)s %(asctime)s',
        },
        'standard': {

            'format' : "%(asctime)-15s %(name)-5s %(levelname)-8s %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
    },

    'handlers': {
        'null': {
            'level':'DEBUG',
            'class':'django.utils.log.NullHandler',
        },
        'logfile': {
            'level':'INFO',
            # 'class': 'logging.handlers.RotatingFileHandler',
            'class': 'logging.FileHandler',
            'filename':  "/home/ubuntu/aysaqorder/QorderWebLog/QOrderLog_aysa.txt",
            'formatter': 'standard',
        },
        'console':{
            'level':'INFO',
            'class':'logging.StreamHandler',
            'formatter': 'standard'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': True,
            'level':'WARN',
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'qorderweb': {
            'handlers': ['console', 'logfile'],
            'level': 'INFO',
        },
    }
}